export const animations = {
    'scale-up-down': 'scaleKeyframe 0.3s ease-in-out',
    'scale-2-up-down': 'scaleKey2frame 0.7s ease-in-out forwards',
    'scale-3-up-down': 'scale3Keyframe 0.7s ease-in-out',
    'left-top': 'leftTop 0.3s ease-in-out forwards',
    'up-opacity': 'elementUpKeyframe 0.5s ease-in-out forwards',
    'down-opacity': 'elementDownKeyframe 0.5s ease-in-out forwards',
    top: 'top 0.3s ease-in-out forwards',
    'right-top': 'rightTop 0.3s ease-in-out forwards',
    right: 'right 0.3s ease-in-out forwards',
    'right-down': 'rightDown 0.3s ease-in-out forwards',
    down: 'down 0.3s ease-in-out forwards',
    'left-down': 'leftDown 0.3s ease-in-out forwards',
    left: 'left 0.3s ease-in-out forwards',
};
