packageExtensions:
    '@aws-sdk/core@3.436.0':
        dependencies:
            tslib: '*'
    '@nestjs/cache-manager@*':
        dependencies:
            '@nestjs/core': ^9.0.0

yarnPath: .yarn/releases/yarn-4.1.0.cjs
