enum UserActivityType {
    ACCESS = 'ACCESS', // 접속
    LOGIN = 'LOGIN', // 로그인
    LOGOUT = 'LOGOUT', // 로그아웃
    POST_CREATED = 'POST_CREATED', // 게시글 생성
    POST_UPDATED = 'POST_UPDATED', // 게시글 수정
    POST_DELETED = 'POST_DELETED', // 게시글 삭제
    COMMENT_CREATED = 'COMMENT_CREATED', // 댓글 생성
    COMMENT_UPDATED = 'COMMENT_UPDATED', // 댓글 수정
    COMMENT_DELETED = 'COMMENT_DELETED', // 댓글 삭제
    REPLY_COMMENT_CREATED = 'REPLY_COMMENT_CREATED', // 대댓글 생성
    REPLY_COMMENT_UPDATED = 'REPLY_COMMENT_UPDATED', // 대댓글 수정
    REPLY_COMMENT_DELETED = 'REPLY_COMMENT_DELETED', // 대댓글 삭제
    FOLLOW_CREATED = 'FOLLOW_CREATED', // 팔로우 생성
    FOLLOW_UPDATED = 'FOLLOW_UPDATED', // 팔로우 토글
    FOLLOW_DELETED = 'FOLLOW_DELETED', // 팔로우 삭제
    ENTITY_CREATED = 'ENTITY_CREATED', // 개체 생성
    ENTITY_UPDATED = 'ENTITY_UPDATED', // 개체 수정
    ENTITY_DELETED = 'ENTITY_DELETED', // 개체 삭제
    ENTITY_WEIGHT_CREATED = 'ENTITY_WEIGHT_CREATED', // 개체 몸무게 생성
    ENTITY_WEIGHT_UPDATED = 'ENTITY_WEIGHT_UPDATED', // 개체 몸무게 수정
    ENTITY_WEIGHT_DELETED = 'ENTITY_WEIGHT_DELETED', // 개체 몸무게 삭제
    CALENDAR_CREATED = 'CALENDAR_CREATED', // 캘린더 생성
    CALENDAR_UPDATED = 'CALENDAR_UPDATED', // 캘린더 수정
    CALENDAR_DELETED = 'CALENDAR_DELETED', // 캘린더 삭제
    PROFILE_UPDATED = 'PROFILE_UPDATED', // 프로필 수정
    WITHDRAWAL = 'WITHDRAWAL', // 회원탈퇴
}

export { UserActivityType };
