version: '3.1'
services:
    mongodb:
        image: arm64v8/mongo:6.0
        platform: linux/arm64/v8
        container_name: reptalie-region-mongodb-6.0
        ports:
            - 27017:27017
        restart: always
        environment:
            - MONGO_INITDB_ROOT_USERNAME=admin
            - MONGO_INITDB_ROOT_PASSWORD=reptalieregionpassword1234
            - MONGO_INITDB_DATABASE=reptalie-region-local
        volumes:
            - type: bind
              source: ./data
              target: /data/db
