import { Inter } from 'next/font/google';
import ReactQueryProviders from '../contexts/react-query/providers';
import { IReactNode } from '<React>';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
    viewport: {
        initialScale: 1,
        maximumScale: 1,
    },
};

export default function RootLayout({ children }: IReactNode) {
    return (
        <html lang="en">
            <body className={`${inter.className} overflow-hidden`}>
                <main>
                    <ReactQueryProviders>{children}</ReactQueryProviders>
                </main>
            </body>
        </html>
    );
}
