import { Inter } from 'next/font/google';
import ReactQueryProviders from '../contexts/react-query/providers';
import { IReactNode } from '<React>';
import './globals.css';
import RouterComponentContext from '@/contexts/router/RouterContext';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
    viewport: {
        initialScale: 1,
        maximumScale: 1,
        userScalable: false,
    },
};

export default function RootLayout({ children }: IReactNode) {
    return (
        <html lang="en">
            <body className={`${inter.className} overflow-hidden`}>
                <RouterComponentContext>
                    <main className="absolute w-full h-full ">
                        <ReactQueryProviders>{children}</ReactQueryProviders>
                        <div id="modal" />
                        <div id="bottomSheet" />
                        <div id="toast" />
                        <div id="alert" />
                    </main>
                </RouterComponentContext>
            </body>
        </html>
    );
}
