import ReactQueryProviders from 'contexts/react-query/providers';
import { Inter } from 'next/font/google';
import { IReactNode } from '<React>';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({ children }: IReactNode) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <main>
                    <ReactQueryProviders>{children}</ReactQueryProviders>
                </main>
            </body>
        </html>
    );
}
