name: Deploy to EC2 with Auto Scaling

on:
    push:
        branches:
            - main

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        environment: production
        steps:
            - name: Check out the repository
              uses: actions/checkout@v4

            - name: Create .env.production file
              run: |
                  cat <<EOF > apps/crawl-nest/.env.production
                  ${{ secrets.ENV_PRODUCTION }}
                  EOF

            - name: Configure AWS credentials
              uses: aws-actions/configure-aws-credentials@v4
              with:
                  aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  aws-region: ap-northeast-2

            - name: Set Docker image tag
              run: echo "IMAGE_TAG=$(echo $GITHUB_SHA | cut -c1-7)" >> $GITHUB_ENV

            - name: Log in to Amazon ECR
              run: |
                  aws ecr get-login-password --region ap-northeast-2 | docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.ap-northeast-2.amazonaws.com

            - name: Build Docker image
              run: |
                  docker build -t nestjs-app-repo:${{ env.IMAGE_TAG }} -f dockers/nest-js-server/Dockerfile .

            - name: Tag Docker image
              run: |
                  docker tag nestjs-app-repo:${{ env.IMAGE_TAG }} ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.ap-northeast-2.amazonaws.com/nestjs-app-repo:${{ env.IMAGE_TAG }}

            - name: Push Docker image to ECR
              run: |
                  docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.ap-northeast-2.amazonaws.com/nestjs-app-repo:${{ env.IMAGE_TAG }}
